# Copyright (c) 2022 Bennett Helm{{{
# SPDX-License-Identifier: MIT

# Aristotle-32 Keymap
#
# This keymap will be converted by the `keymap.py` script into a .pdf file
# representing the layout of the keyboard.
#
# The keymap is presented as a .yaml file that consists of a `keyboard` item
# that specifies both `rows` and `columns` (as integers), and a series of layer
# names. Each layer must have the following items, with corresponding number of
# elements:
#   `keys`:      list of rows, where each row is a list of keys
#   `rowcombos`: list of rows, where each row is a list of combos between keys
#                on that row. There should be 2 fewer items in a row than the
#                number of columns.
#   `colcombos`: list of rows, where each row is a list of combos between keys
#                on vertically adjacent columns. There should be 1 fewer row in
#                this list than the number of rows on the keyboard overall.
# Each of these keys and combos is LaTeX string to be printed in the keyboard
# layout. Locations where a key should not be printed are identified as `None`.
#
# Optionally, each layer *may* include the following lists of [row_number,
# column_number], both 0-based:
#   `lines`:   keys to receive a horizontal line dividing them in half
#   `shading`: keys to be shaded
#
# Hint: Certain strings in YAML files must be escaped or quoted. Using single
# quotes is best where possible, and a single quote character can be
# represented within single quotes by doubling it: `''''` in a field will
# produce `'`. (If using double quotes, `\` must itself be escaped, and so will
# need to be doubled up; hence `\\\\\\` will produce `\\\`.)}}}

keyboard:
    name: Aristotle 32 (2022)
    rows: 4
    columns: 10

dvorak:  # {{{
    keys: [
        [None, '<\\,', '>\\.', P, Y, F, G, C, R, None],
        ['"\\\textquotesingle', O, E, U, I, D, H, T, N, L],
        ['A\\\shift', Q\\\ctrl, J\\\Alt, K\\\cmd, X,
        B, M\\\cmd, W\\\Alt, V\\\ctrl, S\\\shift],
        [None, None, None, ':\\\textsc{sym}', '\backdel\\\textsc{num}',
            '\phantom{M}\vtextvisiblespace\phantom{M}\\\textsc{fun}',
            '{/}~~?\\\textsc{gui}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '"\\\textquotesingle', '\textsc{def}', '', '', ''],
        ]
    colcombos: [
        ['', '\{', '\esc', '*', '', '', '"', '\return', '\}', ''],
        [';~~:', '{[}~~\{', '\tab', '(', '', '', ')', ':', '{]}~~\}', 'Z'],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    lines: [[1,0], [1,1], [1,2], [1,3], [1,6], [1,7], [1,8], [1,9],
            [0,3], [0,4], [0,5], [0,6]]
# }}}

number:  # {{{
    keys: [
        [None, \&, '*', ยง, \textasciitilde, '"', 7, 8, 9, None],
        [\tab, \$, \%, \textasciicircum, \textasciigrave, '>\\.', 4, 5, 6, '+\\='],
        ['\phantom{X}\\\shift', '!\\\ctrl', '@\\\Alt', \#\\\cmd, '$^{\circ}$',
        0, 1\\\cmd, 2\\\Alt, 3\\\ctrl, \_~~-\\\shift],
        [None, None, None, '\textsc{trns}', '\textsc{trns}',
            '\textsc{trns}', '|\\\textbackslash', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '0', '.', ''],
        ['', '', '', '', '\textsc{def}', '', '', ''],
        ]
    colcombos: [
        ['', '\{', '\esc', '*', '', '', '"', '\return', '\}', ''],
        ['\textsc{num lk}', '{[}~~\{', '\tab', '(', '', '', ')', ':', '{]}~~\}', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0,4]]
    lines: [[1,0], [1,1], [1,2], [1,3], [1,6], [1,7], [1,8], [1,9]]
# }}}

function:  # {{{
    keys: [
        [None, F7, F8, F9, F12,
        \faVolumeUp, Home, \arrowkeyup, PgUp, None],
        [\tab, F4, F5, F6, F11, \faVolumeDown, \arrowkeyleft, \arrowkeydown, \arrowkeyright, \faSunO],
        ['\phantom{X}\\\shift', F1\\\ctrl, F2\\\Alt, F3\\\cmd, F10,
        \faVolumeOff, End\\\cmd, '\phantom{X}\\\Alt', PgDn\\\ctrl, \faCircleThin\\\shift],
        [None, None, None, '\textsc{trns}', '\textsc{trns}',
            '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '\textsc{def}', '', '', ''],
        ]
    colcombos: [
        ['', '', '', '', '', '', '\return', '', '', ''],
        ['\textsc{fun lk}', '', '', '\esc', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0,5]]
    lines: [[1,0], [1,1], [1,2], [1,3], [1,6], [1,7], [1,8], [1,9]]
# }}}

gui:  # {{{
    keys: [
        [None, '', Mouse\\\arrowkeyup, Wheel\\\arrowkeyup, Accel\\2,
        Show\\Wins, Prev\\Win, Win\\Big, Next\\Win, None],
        ['\faUsb/\faBluetoothB\\toggle', Mouse\\\arrowkeyleft, Mouse\\\arrowkeydown, Mouse\\\arrowkeyright, Accel\\1,
        Show\\App, Win\\1/3 L, Win\\Small, Win\\1/3 R, \faBluetoothB~1],
        ['\phantom{X}\\\shift', '\phantom{X}\\\ctrl', '\phantom{X}\\\Alt', Wheel\\\arrowkeydown, Accel\\0,
        Show\\Desk, Win\\Left, Win\\Center, Win\\Right, \faBluetoothB~2],
        [None, None, None, Right\\But, Left\\But, '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '\textsc{def}', '', '', ''],
        ]
    colcombos: [
        ['', \faBluetoothB Clear, '', '', '', '', '', '', '', ''],
        ['\textsc{gui lk}', '', '', '', '', '', '\return', '', '', '\faBluetoothB~3'],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0,6]]
    lines: [[1,0], [1,1], [1,2]]
# }}}

symbols:  # {{{
    keys: [
        [None, '', '', '*', '', '', '"', '', '', None],
        ['<', '\{', '[', '(', '', '$^{\circ}$', ')', ']', '\}', '>'],
        [':\\;', '', '', '', '', '', '', ':', '', 'ยง'],
        [None, None, None, '\textsc{trns}', '\textsc{trns}', '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '\textsc{def}', '', '', ''],
        ]
    colcombos: [
        ['', '', '\esc', '', '', '', '', '\return', '', ''],
        ['', '', '\tab', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0,3]]
    lines: []
# }}}

# vim: fdm=marker ft=M
