# Copyright (c) 2022 Bennett Helm{{{
# SPDX-License-Identifier: MIT

# Aristotle-32 Keymap
#
# This keymap will be converted by the `keymap.py` script into a .pdf file
# representing the layout of the keyboard.
#
# The keymap is presented as a .yaml file that consists of a `keyboard` item
# that specifies both `rows` and `columns` (as integers), and a series of layer
# names. Each layer must have the following items, with corresponding number of
# elements:
#   `keys`:      list of rows, where each row is a list of keys
#   `rowcombos`: list of rows, where each row is a list of combos between keys
#                on that row. There should be 2 fewer items in a row than the
#                number of columns.
#   `colcombos`: list of rows, where each row is a list of combos between keys
#                on vertically adjacent columns. There should be 1 fewer row in
#                this list than the number of rows on the keyboard overall.
# Each of these keys and combos is LaTeX string to be printed in the keyboard
# layout. Locations where a key should not be printed are identified as `None`.
#
# Optionally, each layer *may* include the following lists of [row_number,
# column_number], both 0-based:
#   `lines`:   keys to receive a horizontal line dividing them in half
#   `shading`: list of keys to be shaded and corresponding colors
#
# Hint: Certain strings in YAML files must be escaped or quoted. Using single
# quotes is best where possible, and a single quote character can be
# represented within single quotes by doubling it: `''''` in a field will
# produce `'`. (If using double quotes, `\` must itself be escaped, and so will
# need to be doubled up; hence `\\\\\\` will produce `\\\`.)}}}

keyboard:
    name: Aristotle 32 (2022)
    rows: 4
    columns: 10

dvorak:  # {{{
    # TODO: Figure out something for leftmost thumb key!
    keys: [
        ['"\\\textquotesingle', '<\\,', '>\\.', P, Y, F, G, C, R, L],
        [A\\\shift, O\\\ctrl, E\\\Alt, U\\\cmd, I, D, H\\\cmd, T\\\Alt, N\\\ctrl, S\\\shift],
        [None, Q, J, K, X, B, M, W, V, None],
        [None, None, None, ';\\\textsc{mac}', '\backdel\\\textsc{num}',
            '\phantom{M}\vtextvisiblespace\phantom{M}\\\textsc{fun}',
            '{/}~~?\\\textsc{gui}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '+\\=', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '!', '\#', '', '', '', 'Z', ''],
        ['', '', '', '', '\rotatebox{90}{\textsc{dvo}}', '', '', ''],
        ]
    colcombos: [
        ['', '\{', '\esc', '*', '', '', '"', '\return', '\}', ''],
        ['', '{[}~~\{', '\tab', '(', '', '', ')', ':', '{]}~~\}', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    lines: [[2,0], [2,1], [2,2], [2,3], [2,6], [2,7], [2,8], [2,9],
            [0,3], [0,4], [0,5], [0,6]]
# }}}

number:  # {{{
    # TODO: Swap COMMAs and GRAVE?
    keys: [
        [\tab, \&, '*', ยง, '', \textasciigrave, 7, 8, 9, '+\\='],
        ['\textasciitilde\\\shift', \$\\\ctrl, \%\\\Alt, \textasciicircum\\\cmd, '<\\,', '>\\.', 4\\\cmd, 5\\\Alt, 6\\\ctrl, -~~\_\\\shift],
        [None, '!', '@', \#, '$^{\circ}$', 0, 1, 2, 3, None],
        [None, None, None, '\textsc{trns}', '\textsc{trns}',
            '\textsc{trns}', '|\\\textbackslash', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '+\\=', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '!', '\#', '', '', '', '', ''],
        ['', '', '', '', '\rotatebox{90}{\textsc{dvo}}', '', '', ''],
        ]
    colcombos: [
        ['\textsc{num lk}', '\{', '\esc', '*', '', '', '"', '\return', '\}', ''],
        ['', '{[}~~\{', '\tab', '(', '', '', ')', ':', '{]}~~\}', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading:
        [0,4]: black
        [3,4]: green
        [2,4]: yellow
        [3,5]: yellow
    lines: [[2,0], [2,1], [2,2], [2,3], [2,6], [2,7], [2,8], [2,9]]
# }}}

function:  # {{{
    keys: [
        [\tab, F7, F8, F9, F12, \faVolumeUp, Home, \arrowkeyup, PgUp, \faSunO],
        ['@\\\shift', F4\\\ctrl, F5\\\Alt, F6\\\cmd, F11, \faVolumeDown, \arrowkeyleft\\\cmd, \arrowkeydown\\\Alt, \arrowkeyright\\\ctrl, \faCircleThin\\\shift],
        [None, F1, F2, F3, F10, \faVolumeOff, End, '\textsc{repeat}', PgDn, None],
        [None, None, None, '\textsc{trns}', '\shift\backdel',
            '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '\rotatebox{90}{\textsc{dvo}}', '', '', ''],
        ]
    colcombos: [
        ['\textsc{fun lk}', '', '\esc', '', '', '', '', '\return', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading:
        [0,5]: black
        [2,0]: yellow
        [1,7]: yellow
    lines: [[2,0], [2,1], [2,2], [2,3], [2,6], [2,7], [2,8], [2,9]]
# }}}

gui:  # {{{
    # TODO: Fix homerow mods!
    keys: [
        ['\faUsb/\faBluetoothB\\toggle', '', M \arrowkeyup, Wheel\\\arrowkeyup, Accel\\2, Show\\Wins, Prev\\Win, Win\\Big, Next\\Win, \faBluetoothB~1],
        ['\capslock', M \arrowkeyleft\\\ctrl, M \arrowkeydown\\\Alt, M \arrowkeyright\\\cmd, Accel\\1, Show\\App, 'W $\frac{1}{3}$ L\\\cmd', 'W Sm\\\Alt', 'W $\frac{1}{3}$ R\\\ctrl', \faBluetoothB~2\\\shift],
        [None, '\textsc{caps}\\\textsc{word}', '\phantom{X}', Wheel\\\arrowkeydown, Accel\\0, Show\\Desk, Win L, Win C, Win R, None],
        [None, None, None, Right\\But, Left\\But, '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '\rotatebox{90}{\small Mdl But}', '\rotatebox{90}{\textsc{dvo}}', '', '', ''],
        ]
    colcombos: [
        ['\textsc{gui lk}', \faBluetoothB Clear, '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '\return', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading:
        [0,6]: black
        [1,2]: green
        [2,0]: red
        [3,1]: green
        [2,9]: red
    lines: [[2,1], [2,2], [2,3], [2,6], [2,7], [2,8], [2,9]]
# }}}

macros:  # {{{
    keys: [
        ['"W', '', '', '', '', '', '', '', '', ''],
        ['', '', '\emph{e}W', '', '', '', '', '', 'Name', ''],
        [None, '', '', '', '', '\textbf{b}W', '', '', '', None],
        [None, None, None, '', '', '', '', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ]
    colcombos: [
        ['', '', '', '', '', '', '"W', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading:
        [0,3]: black
#       [1,2]: green
#       [2,0]: red
#       [3,1]: green
#       [2,9]: red
#   lines: [[2,1], [2,2], [2,3], [2,6], [2,7], [2,8], [2,9]]
# }}}

# vim: fdm=marker ft=M
