# Aristotle-33 Keymap

# This script will convert a properly formatted .yaml file specifying a keymap
# into a LaTeX file, which is then run to generate a .pdf of the keymap.

# The keymap is presented as a .yaml file that consists of a series of layer
# names. Each layer must have the following items, with corresponding number of
# elements:

# - `top`: top row (10 keys)
# - `mid`dle: middle row (10 keys)
# - `bot`tom: bottom row (10 keys)
# - `thumb`: thumb row (10 keys)
# - `tcomb`: combos between horizontally adjacent top-row keys (8 items)
# - `mcomb`: combos between horizontally adjacent middle-row keys (8 items)
# - `bcomb`: combos between horizontally adjacent bottom-row keys (8 items)
# - `tmcomb`: combos between vertically adjacent keys between top and middle
#             rows (10 items)
# - `mbcomb`: combos between vertically adjacent keys between middle and bottom
#             rows (10 items)

# Each of these items is a list of LaTeX strings to be printed in the keyboard
# layout. Locations where a key should not be printed are identified as `None`.

# Optionally, each layer *may* include the following lists of [row_number,
# column_number], both 0-based:

# - `lines`: keys to receive a horizontal line dividing them in half
# - `shading`: keys to be shaded

# Hint: Certain strings in YAML files must be escaped or quoted. Using single
# quotes is best where possible, and a single quote character can be
# represented within single quotes by doubling it: `''''` in a field will
# produce `'`. (If using double quotes, `\` must itself be escaped, and so will
# need to be doubled up; hence `\\\\\\` will produce `\\\`.)


dvorak:
    top: ['"\\''', '<\\,', '>\\.', P, Y, F, G, C, R, L]
    mid: [A, O, E, U, I, D, H, T, N, S]
    bot: [';~~:\\\shift', Q\\\ctrl, J\\\Alt, K\\\cmd, X,
          B, M\\\cmd, W\\\Alt, V\\\ctrl, Z\\\shift]
    thumb: [None, None, None, None, '\backdel\\\textsc{num}',
            '\phantom{M}\vtextvisiblespace\phantom{M}\\\textsc{fun}',
            '{/}~~?\\\textsc{gui}', None, None, None]
    tcomb: [\tab, \esc, '\{\\{[}', '', '', '\}\\{]}', '', \backdel]
    mcomb: ['"', '?', '(', '', '', ')', \return, '']
    bcomb: ['', '', '', '', '', '', '', '']
    tmcomb: ['', '"', '!','', '', '', -~~\_, =~~+, '', '']
    mbcomb: ['', '', '', '', '', '', '', '', '', '']
    lines: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 6], [1, 7], [1, 8], [1, 9],
            [0, 4], [0, 5], [0, 6]]

number:
    top: ['\textsc{num}\\\textsc{lock}', \&, '*', ยง, \textasciitilde, '"', 7, 8, 9, '+\\=']
    mid: [\tab, \$, \%, \textasciicircum, \textasciigrave,
          ":", 4, 5, 6, \_\\-]
    bot: [\shift, '!', '@', \#, '$^{\circ}$', 0, 1, 2, 3, '']
    thumb: [None, None, None, None, '\textsc{trns}',
            '\textsc{trns}', '|\\\textbackslash', None, None, None]
    tcomb: ['', \esc, '\{\\{[}', '', '', '\}\\{]}', '', \backdel]
    mcomb: ['"', '', '(', '', '', ')', \return, '']
    bcomb: ['', '', '', '', '', '0', '.', '']
    tmcomb: ['', '"', '', '', '', '', -~~\_, =~~+, '', '']
    mbcomb: ['', '', '', '', '', '', '', '', '', '']
    shading: [[0, 4]]

function:
    top: ['\textsc{func}\\\textsc{lock}', F7, F8, F9, F12,
          \faVolumeUp, Home, \arrowkeyup, PgUp, \faSunO]
    mid: ['\textsc{reset}', F4, F5, F6, F11,
          \faVolumeDown, \arrowkeyleft, \arrowkeydown, \arrowkeyright, \faCircleThin]
    bot: [\shift, F1\\\ctrl, F2\\\Alt, F3\\\cmd, F10,
          \faVolumeOff, End, '', PgDn, \capslock]
    thumb: [None, None, None, None, '\textsc{trns}',
            '\textsc{trns}', '\textsc{trns}', None, None, None]
    tcomb: ['', \esc, '', '', '', '', '', '']
    mcomb: ['', '', '', '', '', '', \return, '']
    bcomb: ['', '', '', '', '', '', '', '']
    tmcomb: ['', '', '', '', '', '', '', '', '', '']
    mbcomb: ['', '', '', '', '', '', '', '', '', '']
    shading: [[0, 5]]
    lines: [[1, 1], [1, 2], [1, 3]]

gui:
    top: [\faBluetoothB / \faUsb\\toggle, '', Mouse\\\arrowkeyup, Wheel\\\arrowkeyup, Accel\\2,
          '', Prev\\Win, Win\\Big, Next\\Win, \faBluetoothB~1]
    mid: ['', Mouse\\\arrowkeyleft, Mouse\\\arrowkeydown, Mouse\\\arrowkeyright, Accel\\1,
          '', Win\\1/3 L, Win\\Small, Win\\1/3 R, \faBluetoothB~2]
    bot: [\shift, \ctrl, '', Wheel\\\arrowkeydown, Accel\\0,
          '', Win\\Left, Win\\Center, Win\\Right, \faBluetoothB~3]
    thumb: [None, None, None, None, Left\\But,
            Right\\But,
            '\textsc{trns}', None, None, None]
    tcomb: ['', '', '', '', '', '', '', '']
    mcomb: ['', '', '', '', '', '', \return, '']
    bcomb: ['', '', '', '', '', '', '', '']
    tmcomb: [\faBluetoothB Clear, '', '', '', '', '', '', '', '', '']
    mbcomb: ['', '', '', '', '', '', '', '', '', '']
    shading: [[0, 6]]
