# Aristotle-33 Keymap
#
# This keymap will be converted by the `keymap.py` script into a .pdf file
# representing the layout of the keyboard.
#
# The keymap is presented as a .yaml file that consists of a `keyboard` item
# that specifies both `rows` and `columns` (as integers), and a series of layer
# names. Each layer must have the following items, with corresponding number of
# elements:
#   `keys`:      list of rows, where each row is a list of keys
#   `rowcombos`: list of rows, where each row is a list of combos between keys
#                on that row. There should be 2 fewer items in a row than the
#                number of columns.
#   `colcombos`: list of rows, where each row is a list of combos between keys
#                on vertically adjacent columns. There should be 1 fewer row in
#                this list than the number of rows on the keyboard overall.
# Each of these keys and combos is LaTeX string to be printed in the keyboard
# layout. Locations where a key should not be printed are identified as `None`.
#
# Optionally, each layer *may* include the following lists of [row_number,
# column_number], both 0-based:
#   `lines`:   keys to receive a horizontal line dividing them in half
#   `shading`: keys to be shaded
#
# Hint: Certain strings in YAML files must be escaped or quoted. Using single
# quotes is best where possible, and a single quote character can be
# represented within single quotes by doubling it: `''''` in a field will
# produce `'`. (If using double quotes, `\` must itself be escaped, and so will
# need to be doubled up; hence `\\\\\\` will produce `\\\`.)

keyboard:
    name: Aristotle 33 (2021)
    rows: 4
    columns: 10

dvorak:
    keys: [
        ['"\\''', '<\\,', '>\\.', P, Y, F, G, C, R, L],
        [A\\\shift, O\\\ctrl, E\\\Alt, U\\\cmd, I,
        D, H\\\cmd, T\\\Alt, N\\\ctrl, S\\\shift],
        [:\\;, Q, J, K, X, B, M, W, V, Z],
        [None, None, None, None, '\backdel\\\textsc{num}',
            '\phantom{M}\vtextvisiblespace\phantom{M}\\\textsc{fun}',
            '{/}~~?\\\textsc{gui}', None, None, None],
        ]
    rowcombos: [
        ['', \esc, '(', '\{\\{[}', '\}\\{]}', ')', \return, ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ]
    colcombos: [
        ['', '', '','', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    lines: [[2, 0], [2, 1], [2, 2], [2, 3], [2, 6], [2, 7], [2, 8], [2, 9],
            [0, 4], [0, 5], [0, 6]]

number:
    keys: [
        ['\textsc{num}\\\textsc{lock}', \&, '*', ยง, \textasciitilde, '"', 7, 8, 9, '+\\='],
        [\tab\\\shift, \$\\\ctrl, \%\\\Alt, \textasciicircum\\\cmd, \textasciigrave,
        :, 4\\\cmd, 5\\\Alt, 6\\\ctrl, -~~\_\\\shift],
        ['', '!', '@', \#, '$^{\circ}$', 0, 1, 2, 3, '>\\.'],
        [None, None, None, None, '\textsc{trns}',
            '\textsc{trns}', '|\\\textbackslash', None, None, None],
        ]
    rowcombos: [
        ['', \esc, '(', '\{\\{[}', '\}\\{]}', ')', \return, ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '0', '.', ''],
        ['', '', '', '', '', '', '', ''],
        ]
    colcombos: [
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0, 4]]
    lines: [[2, 0], [2, 1], [2, 2], [2, 3], [2, 6], [2, 7], [2, 8], [2, 9]]

function:
    keys: [
        ['\textsc{func}\\\textsc{lock}', F7, F8, F9, F12,
          \faVolumeUp, Home, \arrowkeyup, PgUp, \faSunO],
        [\shift, F4\\\ctrl, F5\\\Alt, F6\\\cmd, F11,
          \faVolumeDown, \arrowkeyleft\\\cmd, \arrowkeydown\\\Alt, \arrowkeyright\\\ctrl, \faCircleThin\\\shift],
        ['', F1, F2, F3, F10, \faVolumeOff, End, '', PgDn, \capslock],
        [None, None, None, None, '\textsc{trns}',
            '\textsc{trns}', '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', \esc, '', '', '', '', \return, ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ]
    colcombos: [
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0, 5]]
    lines: [[2, 1], [2, 2], [2, 3], [2, 6], [2, 7], [2, 8], [2, 9]]

gui:
    keys: [
        ['\faUsb/\faBluetoothB\\toggle', '', Mouse\\\arrowkeyup, Wheel\\\arrowkeyup, Accel\\2,
        Show\\Wins, Prev\\Win, Win\\Big, Next\\Win, \faBluetoothB~1],
        ['', Mouse\\\arrowkeyleft, Mouse\\\arrowkeydown, Mouse\\\arrowkeyright, Accel\\1,
        Show\\App, Win\\1/3 L, Win\\Small, Win\\1/3 R, \faBluetoothB~2],
        [\shift, \ctrl, '', Wheel\\\arrowkeydown, Accel\\0,
        Show\\Desk, Win\\Left, Win\\Center, Win\\Right, \faBluetoothB~3],
        [None, None, None, None, Left\\But, Right\\But, '\textsc{trns}', None, None, None],
        ]
    rowcombos: [
        ['', '', '', '', '', '', \return, ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', ''],
        ]
    colcombos: [
        [\faBluetoothB Clear, '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', ''],
        ]
    shading: [[0, 6]]

# \faBluetoothB / \faUsb\\toggle
