on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Aristotle33)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=aristotle33 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Aristotle33 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: Aristotle33 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 aristotle33.uf2
      - name: Archive (Aristotle33)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: aristotle33.uf2
      - name: West Build (Aristotle33 modpin A)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=aristotle33_a -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Aristotle33 modpin A Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 aristotle33a.uf2
      - name: Archive (Aristotle33 modpin A)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: aristotle33a.uf2
      - name: West Build (Aristotle33 modpin B)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=aristotle33_b -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Aristotle33 modpin B Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 aristotle33_b.uf2
      - name: Archive (Aristotle33 modpin B)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: aristotle33_b.uf2
